BarkBuddies/BarkBuddies/Models/PetMatch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace BarkBuddies.Models
{
    public class PetMatch
    {
        [JsonPropertyName("PetId")]
        public int PetMatchId { get; set; } //animal ID from petfinder
        
        public string Name { get; set; }
        
        public string Age { get; set; }
        
        public string Gender { get; set; }
        
        public string Size { get; set; }
        
        public string Breed { get; set; }
        
        public string Url { get; set; }
        
        public string PhotoUrl { get; set; }
        
        public string Organization { get; set; }
    }
}

BarkBuddies/BarkBuddies/Controllers/PetController.cs
using System.Linq;
using System.Threading.Tasks;
using BarkBuddies.Data;
using BarkBuddies.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BarkBuddies.Controllers
{

    public class PetController : Controller
    {
        private readonly AnimalContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public PetController(AnimalContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var currentUser = GetCurrentUserAsync().Result;
                return View(await _context.Pets.Where(x => x.Owner.Equals(currentUser)).ToListAsync());
            }
            else
            {
                return RedirectToAction("Index", "UserProfile");
            }
        }

        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .FirstOrDefaultAsync(m => m.PetId == id);
            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        [Authorize]
        public IActionResult Create()
        {         
            {
                return View();              
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Age,Gender,Size,Breed")] Pet pet)
        {           
                if (ModelState.IsValid)
                {
                    var currentUser = await GetCurrentUserAsync();
                    var thisPet = pet;
                    thisPet.Owner = currentUser;
                    _context.Add(thisPet);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(pet);           
        }

        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets.FindAsync(id);
            if (pet == null)
            {
                return NotFound();
            }
            return View(pet);
        }
 
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PetId,Name,Age,Gender,Size,Breed")] Pet pet)
        {
            if (id != pet.PetId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetExists(pet.PetId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new {id});
            }
            return View(pet);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pet = await _context.Pets
                .FirstOrDefaultAsync(m => m.PetId == id);

            if (pet == null)
            {
                return NotFound();
            }

            return View(pet);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var pet = await _context.Pets.FindAsync(id);
            _context.Pets.Remove(pet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PetExists(int id)
        {
            return _context.Pets.Any(p => p.PetId == id);
        }

        private async Task<IdentityUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(User);
    }        
}

BarkBuddies/BarkBuddies/Controllers/PetMatchController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using BarkBuddies.Data;
using BarkBuddies.Data.Entities;
using BarkBuddies.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BarkBuddies.Controllers
{
    public class PetMatchController : Controller
    {
        private readonly IAnimalsService _service;
        private readonly AnimalContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private const string Adoptable = "Adoptable";
        private const string NotAdoptable = "Not Adoptable";

        public PetMatchController(IAnimalsService service, AnimalContext context, UserManager<IdentityUser> userManager)
        {
            _service = service;
            _context = context;
            _userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var currentUser = GetCurrentUserAsync().Result;
            var petMatchList = await _context.PetMatch.Where(x => x.User.Equals(currentUser)).ToListAsync();
            foreach (var pet in petMatchList)
            {
                if (pet.Status != Adoptable && _service.Get(pet.PetId.ToString()).Result == null)
                {
                    using (var db = _context)
                    {
                        var result = db.PetMatch.SingleOrDefaultAsync(x => x.PetId == pet.PetId);
                        if (result != null)
                        {
                            result.Result.Status = NotAdoptable;
                            await db.SaveChangesAsync();
                        }
                    }
                    TempData["NotAdoptable"] += $"{pet.Name} has been adopted and updated below. \n";
                }
            }
            return View(petMatchList);
        }

        [Authorize]
        public IActionResult Search()
        {
            var currentUser = GetCurrentUserAsync().Result;
            var details = _service.Get(_context.Pets
                .Where(x => x.Owner.Equals(currentUser)).ToListAsync().Result, 
                GetProfileAsync(currentUser.Id).Result).Result;
            var model = details.Animals.ToList();
            return View(model);
        }
        
        [Authorize]
        public async Task<IActionResult> SavePet(string id)
        {
            var currentUser = GetCurrentUserAsync().Result;
            var pet = _service.Get(id).Result.Animal;
            if (pet != null && _context.PetMatch.Where(x => x.PetId == pet.PetId).Count() == 0)
            {
                var petAge = Age.baby;
                Enum.TryParse(pet.Age, true, out petAge);
                var petSize = Size.small;
                Enum.TryParse(pet.Size, true, out petSize);

                _context.Add(new PetMatch {
                    PetId = pet.PetId,
                    Name = pet.Name,
                    Age = petAge,
                    Gender = pet.Gender,
                    Size = petSize,
                    Breed = pet.Breeds.Primary,
                    Status = Adoptable,
                    Url = pet.Url,
                    User = currentUser});
                await _context.SaveChangesAsync();
                TempData["Success"] = $"{pet.Name} was successfully saved to list!";
            }
            return RedirectToAction("Search");
        }

        [Authorize]
        public async Task<IActionResult> Adopt(string id)
        {
            var currentUser = GetCurrentUserAsync().Result;
            Animal pet;
            try
            {
                pet = _service.Get(id).Result.Animal;
                if (_context.Pets.Where(x => x.Name == pet.Name && x.Breed == pet.Breeds.Primary).Count() == 0)
                {
                    var petAge = Age.baby;
                    Enum.TryParse(pet.Age, true, out petAge);
                    var petSize = Size.small;
                    Enum.TryParse(pet.Size, true, out petSize);

                    _context.Add(new Pet
                    {
                        Name = pet.Name,
                        Age = petAge,
                        Gender = pet.Gender,
                        Size = petSize,
                        Breed = pet.Breeds.Primary,
                        Owner = currentUser
                    });
                    await _context.SaveChangesAsync();
                    TempData["Adopted"] = $"Congratulations! You've adopted {pet.Name}!";

                    var petMatchList = _context.PetMatch.Where(x => x.PetId == pet.PetId).ToListAsync().Result;
                    if (petMatchList.Count() != 0)
                    {
                        using (var db = _context)
                        {
                            for (int i = 0; i < petMatchList.Count; i++)
                            {
                                var result = db.PetMatch.SingleOrDefaultAsync(x => x.PetId == petMatchList[i].PetId);
                                if (result != null)
                                {
                                    result.Result.Status = NotAdoptable;
                                }
                            }
                            await db.SaveChangesAsync();
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            var currentUser = GetCurrentUserAsync().Result;
            int tempId;
            int? petId = int.TryParse(id, out tempId) ? tempId : (int?)null;

            if (petId == null)
            {
                return NotFound();
            }

            var pet = await _context.PetMatch
                .Where(x => x.PetId == petId && x.User == currentUser).FirstOrDefaultAsync();

            if (pet == null)
            {
                return NotFound();
            }
            _context.PetMatch.Remove(pet);
            await _context.SaveChangesAsync();
            TempData["Removed"] = $"{pet.Name} has been removed.";

            return RedirectToAction("Index");
        }

        private async Task<UserProfile> GetProfileAsync(string userId)
        {
            return await _context.UserProfiles.FirstOrDefaultAsync(x => x.User.Id == userId);
        }

        private async Task<IdentityUser> GetCurrentUserAsync() => await _userManager.GetUserAsync(User);
    }
}

BarkBuddies/BarkBuddies/Views/PetMatch/Details.cshtml
@model IEnumerable<Animal>

@{
    ViewData["Title"] = "Details";
}

<h1>View</h1>

<div>
    <h4>PetMatch</h4>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Age)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gender)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Size)
                </th>
                
                <th>
                    @Html.DisplayNameFor(model => model.Url)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrganizationId)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pet in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => pet.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => pet.Age)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => pet.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => pet.Size)
                    </td>
                    
                    <td>
                        @Html.DisplayFor(modelItem => pet.Url)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => pet.OrganizationId)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>

    <a asp-controller="Home" asp-action="Index">Home</a> |
    
        <a  asp-controller="Pets" asp-action="Index">Your Pets</a>
    

</div>

BarkBuddies/BarkBuddies/Views/PetMatch/Index.cshtml
@model IEnumerable<BarkBuddies.Data.Entities.PetMatch>

@{
    ViewData["Title"] = "My Pet Wish List";
}
<h1>Wish List</h1>

@if (Model.Any() == true)
{
    <p>
        @if (TempData.Peek("Adopted") != null)
        {
            @TempData["Adopted"]
        }
        @if (TempData.Peek("NotAdoptable") != null)
        {
            @TempData["NotAdoptable"]
        }
        @if (TempData.Peek("Removed") != null)
        {
            @TempData["Removed"]
        }
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Age)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gender)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Size)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Breed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Age)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Size)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Breed)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <a href="@item.Url" target="_blank">View Profile</a> |
                        @if (item.Status == "Adoptable")
                        {
                            <a asp-action="Adopt" asp-route-id="@item.PetId">Adopt</a>
                        }
                        else
                        {
                            @: Adopt
                        } |
                        <a asp-action="Delete" asp-route-id="@item.PetId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <a asp-controller="PetMatch" asp-action="Search" class="btn btn-primary">Search for pets to add</a>
}
<div>
    <a asp-controller="Pet" asp-action="Index">My Pets</a> |
    <a asp-controller="UserProfile" asp-action="Index">Home</a>
</div>

BarkBuddies/BarkBuddies/Views/PetMatch/Search.cshtml
@model IEnumerable<Animal>

@{
    ViewData["Title"] = "Pet Search";
}
<h1>Matching Pets</h1>

@if (TempData.Peek("Success") != null)
{
    <p>@TempData["Success"]</p>
}

@if (Model.Any())
{
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Age)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Gender)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Size)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Breeds)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Contact)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Url)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pet in Model)
                {
                    <tr>
                        @if (pet.Photos.Count() < 1)
                        {
                            <td>
                                <p>No photo</p>
                            </td>

                        }
                        else
                        {
                            <td>
                                @{
                                    var img = pet.Photos[0].Small;
                                }
                                <img src=@img width=@img .100 />
                            </td>
                        }



                        <td>
                            @Html.DisplayFor(modelItem => pet.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => pet.Age)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => pet.Gender)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => pet.Size)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => pet.Breeds.Primary)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => pet.Contact.Address.City), @Html.DisplayFor(modelItem => pet.Contact.Address.State)
                        </td>
                        <td>
                            <a href="@Html.DisplayFor(modelItem => pet.Url)" target="_blank">View Petfinder Page</a>
                        </td>

                        <td>
                            <a asp-controller="PetMatch" asp-action="SavePet" asp-route-id="@pet.PetId" class="btn btn-primary">Save to Wish List</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <p>Sorry! No pets match your search. Please double check your preferences and search again.</p>
}
<div>
    <a asp-controller="Pet" asp-action="Index">My Pets</a> |
    <a asp-controller="UserProfile" asp-action="Index">Home</a>
</div>